version: '3'
services:
  chatgpt-telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    restart: unless-stopped

  webhook-listener:
    build:
      context: .
      dockerfile: Dockerfile.webhook
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
    environment:
      - SECRET_KEY=your_secret_key_here
    restart: unless-stopped